2022-01-13 20:23:58   Arguments: Namespace(backbone='resnet18', use_netvlad=True, netvlad_clusters=64, use_gem=None, gem_p=3, gem_eps=1e-06, use_sgd=None, use_adagrad=None, momentum=0.9, train_batch_size=4, infer_batch_size=16, margin=0.1, epochs_num=10, patience=3, lr=1e-05, cache_refresh_rate=1000, queries_per_epoch=5000, negs_num_per_query=10, neg_samples_num=1000, seed=0, device='cuda', num_workers=8, val_positive_dist_threshold=25, train_positives_dist_threshold=10, recall_values=[1, 5, 10, 20], datasets_folder='./Datasets_pitts30k', exp_name='default', test_dataset_name=None, test_model_path=None, output_folder='runs/default/2022-01-13_20-23-58')
2022-01-13 20:23:58   The outputs are being saved in runs/default/2022-01-13_20-23-58
2022-01-13 20:23:59   Using 1 GPUs and 12 CPUs
2022-01-13 20:23:59   
Traceback (most recent call last):
  File "/home/franzhd/Aml_project/project_vg/run_train.py", line 35, in <module>
    triplets_ds = datasets_ws.TripletsDataset(
  File "/home/franzhd/Aml_project/project_vg/datasets_ws.py", line 106, in __init__
    super().__init__(args, datasets_folder, dataset_name, split)
  File "/home/franzhd/Aml_project/project_vg/datasets_ws.py", line 60, in __init__
    if not os.path.exists(self.dataset_folder): raise FileNotFoundError(f"Folder {self.dataset_folder} does not exist")
FileNotFoundError: Folder ./Datasets_pitts30k/pitts30k/images/train does not exist

