2022-01-12 19:34:52   Arguments: Namespace(use_netvlad=None, netvlad_clusters=64, use_gem=None, gem_p=3, gem_eps=1e-06, use_sgd=None, use_adagrad=None, momentum=0.9, train_batch_size=4, infer_batch_size=16, margin=0.1, epochs_num=5, patience=3, lr=1e-05, cache_refresh_rate=1000, queries_per_epoch=5000, negs_num_per_query=10, neg_samples_num=1000, seed=0, device='cuda', num_workers=8, val_positive_dist_threshold=25, train_positives_dist_threshold=10, recall_values=[1, 5, 10, 20], datasets_folder='Dataset_st_lucia', exp_name='default', test_dataset_name='st_lucia', test_model_path='./Runs/netvlad_10_0.000001_64/best_model.pth', output_folder='test_runs/default/2022-01-12_19-34-52')
2022-01-12 19:34:52   The outputs are being saved in test_runs/default/2022-01-12_19-34-52
2022-01-12 19:34:52   Using 1 GPUs and 12 CPUs
2022-01-12 19:34:52   Loading test dataset st_lucia from folder Dataset_st_lucia
2022-01-12 19:34:52   Test set: < BaseDataset, st_lucia - #database: 1549; #queries: 1464 >
2022-01-12 19:34:53   Train only conv4 of the ResNet-18 (remove conv5), freeze the previous ones
2022-01-12 19:34:57   
Traceback (most recent call last):
  File "/home/franzhd/Aml_project/project_vg/run_test.py", line 45, in <module>
    model.load_state_dict(model_state_dict)
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GeoLocalizationNet:
	Unexpected key(s) in state_dict: "aggregation.centroids", "aggregation.conv.weight". 

