2022-01-18 19:26:36   Arguments: Namespace(upscale_input=False, downscale_input=False, augment_input='None', backbone='resnet18', use_netvlad=True, netvlad_clusters=64, use_gem=None, gem_p=3, gem_eps=1e-06, use_attention='crn', attention_lr=0.001, use_sgd=None, use_adagrad=None, momentum=0.9, train_batch_size=4, infer_batch_size=16, margin=0.1, epochs_num=5, patience=3, lr=1e-05, cache_refresh_rate=1000, queries_per_epoch=5000, negs_num_per_query=10, neg_samples_num=1000, seed=0, device='cpu', num_workers=8, val_positive_dist_threshold=25, train_positives_dist_threshold=10, recall_values=[1, 5, 10, 20], datasets_folder='Dataset_st_lucia', exp_name='default', test_dataset_name='st_lucia', test_model_path='./Runs/default/2022-01-18_17-37-47/best_model.pth', save_attention_mask=None, output_folder='test_runs/default/2022-01-18_19-26-36')
2022-01-18 19:26:36   The outputs are being saved in test_runs/default/2022-01-18_19-26-36
2022-01-18 19:26:36   Using 1 GPUs and 12 CPUs
2022-01-18 19:26:36   Loading test dataset st_lucia from folder Dataset_st_lucia
2022-01-18 19:26:36   Test set: < BaseDataset, st_lucia - #database: 1549; #queries: 1464 >
2022-01-18 19:26:36   Train only conv4 of the ResNet-18 (remove conv5), freeze the previous ones
2022-01-18 19:26:37   
Traceback (most recent call last):
  File "/home/franzhd/Aml_project/project_vg/run_test.py", line 42, in <module>
    model_state_dict = torch.load(
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/franzhd/.local/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './Runs/default/2022-01-18_17-37-47/best_model.pth'

