2022-01-05 20:16:40   Arguments: Namespace(use_netvlad=None, train_batch_size=4, infer_batch_size=16, margin=0.1, epochs_num=50, patience=3, lr=1e-05, cache_refresh_rate=1000, queries_per_epoch=5000, negs_num_per_query=10, neg_samples_num=1000, seed=0, device='cuda', num_workers=8, val_positive_dist_threshold=25, train_positives_dist_threshold=10, recall_values=[1, 5, 10, 20], datasets_folder='Data/pitts30k/', exp_name='default', output_folder='runs/default/2022-01-05_20-16-40')
2022-01-05 20:16:40   The outputs are being saved in runs/default/2022-01-05_20-16-40
2022-01-05 20:16:40   Using 1 GPUs and 12 CPUs
2022-01-05 20:16:40   
Traceback (most recent call last):
  File "/home/franzhd/Aml_project/project_vg/train.py", line 34, in <module>
    triplets_ds = datasets_ws.TripletsDataset(args, args.datasets_folder, "pitts30k", "train", args.negs_num_per_query)
  File "/home/franzhd/Aml_project/project_vg/datasets_ws.py", line 106, in __init__
    super().__init__(args, datasets_folder, dataset_name, split)
  File "/home/franzhd/Aml_project/project_vg/datasets_ws.py", line 60, in __init__
    if not os.path.exists(self.dataset_folder): raise FileNotFoundError(f"Folder {self.dataset_folder} does not exist")
FileNotFoundError: Folder Data/pitts30k/pitts30k/images/train does not exist

